#Created by Saroj

target = LMS
CC = gcc
Compile.o = $(CC) -c

$(target): main.o htc.o
	$(CC) htc.o main.o -o $@

main.o: main.c
	$(Compile.o) main.c

%.o: %.c %.h
	$(Compile.o) $<

.PHONY: clean

clean:
	$(RM) main.o htc.o

